version: '3'
services:
  node:
    restart: always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    environment:
      - KNOTES_MONGO_URL=mongodb://mongo:27017/knotes?retryWrites=true&w=majority
      - KNOTES_SECRET=secret
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
